apiVersion: v1
kind: Service
metadata:
  name: sys-stat-app-svc
spec:
  selector:
    app: sys-stat-app
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 80
  externalIPs:
    - 10.0.0.110